import { Inter } from 'next/font/google';
import './globals.css';
import { notoSansKR, ptSerif } from '../fonts/index';
// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${notoSansKR.variable} ${ptSerif.variable} ${notoSansKR.className} `}>
                {children}
            </body>
        </html>
    );
}
